
FROM alpine:3
MAINTAINER Markus Juenemann <markus@juenemann.net>

RUN apk update && \
    apk add expat \
            gdbm \
            libbz2 \
            libcrypto1.1 \
            libffi \
            libssl1.1 \
            musl \
            ncurses-libs \
            readline \
            sqlite-libs \
            xz-libs \
            musl-dev \
            readline-dev \
            ncurses-dev \
            zlib-dev \
            openssl-dev \
            gdbm-dev \
            xz-dev \
            sqlite-dev \
            libuuid \
            zlib-dev \
            libffi-dev \
            bzip2-dev \
            expat-dev \
            tcl-dev \
            bluez-dev \
            linux-headers \
            build-base \
            tcl-dev \
            tk-dev \
            tcl \
            tk \
            zlib \
            wget \
            gcc \
            make && \
    rm -rf /var/cache/apk/*

RUN wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py

RUN wget https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz && \
    tar xvfz Python-3.8.1.tgz && \
    cd Python-3.8.1 && \
    ./configure --enable-optimizations && \
    make clean && \
    make && \
    make altinstall && \
    cd - && \
    /usr/local/bin/python3.8 get-pip.py && \
    pip3.8 install --upgrade pip && \
    pip3.8 install tox setuptools nose coverage minimock instrumental && \
    rm -rfv Python-* \
    rm -fv `find /usr/local/lib -name "*.pyc"` && \
    rm -fv `find /usr/local/lib -name "*.pyo"` 


#    akp update && \
#    apk del `apk list --installed | grep '\-dev' | cut -d- -f 1,2` && \
#    apk del gcc make linux-headers build-base && \
#    rm -rf /var/cache/apk/*
